# Agents Guide for ngrok-docs-v2

## Project Overview
This is the ngrok documentation site built on Mintlify. The navigation structure was successfully converted from Docusaurus sidebar-example.js format to Mintlify docs.json format.

## Conversion Status

### ✅ Completed
- **Full conversion** from sidebar-example.js to docs.json structure
- **Preserved hierarchical organization** exactly matching original sidebar
- **Applied "Overview" pattern** for category links (categories that had `link` properties now have those pages as "Overview" child items)
- **Maintained major sections** as groups with proper nesting
- **Root pages** maintained at top level: overview/index, what-is-ngrok, how-ngrok-works, why-ngrok, whats-new
- **All autogenerated content populated** using automated directory scanning

### ✅ Completed (Autogenerated Content)
All autogenerated directories have been successfully scanned and populated:

#### Traffic Policy
- `traffic-policy/getting-started/` - ✅ 2 items
- `traffic-policy/concepts/` - ✅ 6 items  
- `traffic-policy/actions/` - ✅ 25 items
- `traffic-policy/variables/` - ✅ 8 items
- `traffic-policy/examples/` - ✅ 13 items

#### Universal Gateway
- `universal-gateway/examples/` - ✅ 20 items

#### Secure Tunnels
- `agent-sdks/` - ✅ 1 item

#### Guides
- `guides/device-gateway/` - ✅ 7 items
- `guides/identity-aware-proxy/` - ✅ 1 item  
- `using-ngrok-with/` - ✅ 26 items
- `integrations/` - ✅ 103 items (with nested subgroups for each service)

## Automated Scripts Created

### `rebuild-docs-json.js`
Complete script that rebuilds the entire docs.json file to match sidebar-example.js structure exactly.

**Features:**
- Scans all autogenerated directories recursively
- Handles both `.md` and `.mdx` files
- Alphabetically sorts files with `index` files first
- Creates nested subgroups for subdirectories
- Strips file extensions and handles special characters
- Ignores hidden files (starting with `.` or `_`)
- Preserves exact sidebar-example.js hierarchy and structure

**Usage:**
```bash
node rebuild-docs-json.js
```

## Navigation Structure Decisions Made

### HTML Section Dividers
Original Docusaurus had `{type: "html", value: "<div class='menu__section'>Platform</div>"}` and `{type: "html", value: "<div class='menu__section'>Guides</div>"}` - these were converted to logical groupings within the flat navigation structure.

### Category Links → Overview Pattern  
Categories that had `link: { type: "doc", id: "..." }` were converted to have that linked page as the first child item in the group, maintaining the "Overview" concept.

### Preserved Flat Structure
Unlike the initial attempt with tabs, the final structure maintains the flat organization from sidebar-example.js, with major sections as groups and nested subgroups as needed.

### Nested Structure Preservation
Complex nested categories like Universal Gateway > Endpoints > Types > Cloud Endpoints were preserved with the same depth and hierarchy.

### Autogenerated Content Integration
All `{type: "autogenerated", dirName: "..."}` entries were replaced with actual scanned directory contents, creating proper nested subgroups for multi-level directory structures.

## File Processing Rules

1. **File Extensions**: Both `.mdx` and `.md` files included
2. **Index Files**: Listed first in each directory/group
3. **Subdirectories**: Converted to nested subgroups with proper capitalization
4. **File Naming**: Extensions stripped, special characters handled for valid JSON
5. **Sorting**: Alphabetical within each group (index first)
6. **Hidden Files**: Files starting with `.` or `_` ignored, non-documentation files ignored

## Development Commands
Run the rebuild script to regenerate docs.json with latest directory contents:
```bash
node rebuild-docs-json.js
```

Start the Mintlify development server:
```bash
pnpm run dev
```

The server runs at `http://localhost:3000` with hot reloading.

## Final Structure
- **212 total items** across all sections
- **11 autogenerated directories** fully populated
- **Exact 1:1 mapping** with sidebar-example.js structure
- **Valid Mintlify navigation format** confirmed

## Notes
- Original file: `sidebar-example.js` (761 lines) 
- Successfully converted to `docs/docs.json` with all autogenerated content
- Mintlify navigation supports nested groups and mixed content types
- All directory scanning is automated and can be re-run as content changes
- Structure is optimized for Mintlify's navigation rendering
