import clsx from "clsx";
import { NavLink, useLoaderData, useRouteLoaderData } from "@remix-run/react";
import { Button } from "@ngrok/mantle/button";
import { HoverCard, HoverCardContent, HoverCardTrigger } from "@ngrok/mantle/hover-card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@ngrok/mantle/dropdown-menu";
import { Icon } from "@ngrok/mantle/icon";
import { NavBucket, navData } from "~/utils/navData";
import { CaretDown } from "@phosphor-icons/react";
import { DocsLoaderData } from "~/routes/docs+/route";
import { SidebarItem } from "~/utils/sidebar";

/**
 * Get sidebar data, which already has formatted links etc
 *
 */

export default function Navigation(props: any) {
  const data = useRouteLoaderData<DocsLoaderData>("routes/docs+/route");

  const sidebarData = data?.sidebarData;  
  if(!sidebarData || sidebarData.length === 0) {
    return null;
  }

  return (
    <div
      className={clsx(
        `ml-2 relative flex-grow basis-0 items-center space-x-3 hidden md:block`,
        props.className
      )}
    >
      {sidebarData.map((bucket: SidebarItem) => {
        if (!bucket?.title) return null;
        if(bucket.isAutoGenerated)  return null;
        return (
          <HoverCard key={`${bucket.title}-${bucket.path}`}>
            <HoverCardTrigger asChild>
              <Button appearance="link" type="button">
                {bucket.title} <Icon svg={<CaretDown />} />
              </Button>
            </HoverCardTrigger>
            <HoverCardContent className="flex flex-col" >
              {/* Get sidebar data for the bucket here*/}
              {bucket?.children?.map((item: SidebarItem) => {
                // This check should be removed eventually.
                // The data should probably always have a title and path.
                if (!item?.title || !item?.path) return null;
                return (
                  <NavLink key={item.path + item.title}
                      to={item.path}
                      prefetch="intent"
                      aria-label={item.title}
                      className={({ isActive }) =>
                        clsx(
                          "w-full hover:text-sky-500",
                          isActive
                            ? "font-semibold text-sky-500 before:bg-sky-500"
                            : "text-black before:hidden before:bg-slate-300 hover:text-slate-600"
                        )
                      }
                    >
                      {item.title}
                    </NavLink>
                );
              })}
            </HoverCardContent>
          </HoverCard>
        );
      })}
    </div>
  );
}
